export const POKEMONS_LIST = "POKEMONS_LIST";
export const SEARCH_IN_POKEMON_LIST = "SEARCH_IN_POKEMON_LIST";
export const SEARCH_IN_POKEDEX_LIST = "SEARCH_IN_POKEDEX_LIST";
export const ADD_POKEMON = " ADD_POKEMON";
export const REMOVE_POKEMON = " REMOVE_POKEMON";
